### ISSUE TITLE
能和我做一辈子多模态吗

### ISSUE THREAD

**Issue by deuterium-suika** [zjukg/MyGO#1]
还在go，还在go😡

**Comment by jellyterra** [comment]
还在go，还在go😡

**Comment by jellyterra** [comment]
你这个人，只考虑你自己呢 😡

**Comment by alphaply** [comment]
😡😡😡

**Comment by bryce-wan** [comment]
你这个人，满脑子都只想着自己呢

**Comment by yuani114** [comment]
要是没有多模态，瓦塔西😭

**Comment by ziyu-king** [comment]
哈？

**Comment by zhengtianyi13** [comment]
求求你了，我什么都会做的
![soyo](https://github.com/zjukg/MyGO/assets/40736449/0e09fbe3-8720-4b08-848a-e93660e9f782)

**Comment by sorui-qin** [comment]
怎么这么多Go批啊（恼）

**Comment by HairlessVillager** [comment]
Funny Title Is All You Need

![`J})V(RU(QD5_VU$Y 9YV~M](https://github.com/zjukg/MyGO/assets/64526732/5b7e827d-272a-4b75-b7ec-593a04e5403e)

**Comment by Hollow-D** [comment]
为什么要构建多模态.jpg

**Comment by Akisamu** [comment]
……あなた、ご自分のことばかりですのね
![download](https://github.com/user-attachments/assets/47f2b544-e42d-4a36-9119-b760db019b8a)
