### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tokens/textual.pth'

### ISSUE THREAD

**Issue by shuyulou** [zjukg/MyGO#15]
运行发现少了一个文件。还想问一下从哪里可以下载到原始的图片？谢谢！

**Comment by Zhang-Each** [comment]
原始图片可以从过这个仓库提供的文件下载：https://github.com/quqxui/MMRNS
textual.pth的获取方法详见README的data preparation

**Comment by shuyulou** [comment]
谢谢

**Comment by shuyulou** [comment]
您好，我在单卡4090上按照README中的参数运行程序，但是模型在DB15K上的MRR在36左右浮动，请问这是正常现象么

**Comment by Zhang-Each** [comment]
> 您好，我在单卡4090上按照README中的参数运行程序，但是模型在DB15K上的MRR在36左右浮动，请问这是正常现象么

您好，实验结果有一定的浮动是正常现象。README中的参数并不是最优结果对应的配置，您可以尝试调整参数取得更好的结果。我们后续还会对这个仓库中的数据集和代码进行进一步的维护。
