### ISSUE TITLE
对于其他单模态数据集的使用

### ISSUE THREAD

**Issue by ZeyuZhu0120** [zjukg/MyGO#17]
非常感谢作者们扎实的工作，我现在想要尝试用您提供的代码跑WN18和FB15K-237这两个数据集，不知道这个可否实现呢？因为我注意到您的代码中有这些针对于DB15K和MKG-W的专有json文件，不知道这些文件可否通过代码生成在其他数据集上呢？（例如WN18和FB15K-237）
![image](https://github.com/zjukg/MyGO/assets/91859784/cf8eb4b9-0b3b-4061-b4c7-61d41849fb51)

**Comment by Zhang-Each** [comment]
你好，应该是可以的，只需要把对应数据集的文本和图像信息处理成类似的token序列即可。
