### ISSUE TITLE
还在Go还在Go!!!

### ISSUE THREAD

**Issue by AluminiumOxide** [zjukg/MyGO#2]
sir! what can I say!

**Comment by cyanial** [comment]
no sir! man!!!

**Comment by AluminiumOxide** [comment]
> no sir! man!!!

While selective_scan in **man**ba-ssh have its own idea, amazing like a school of KND crawling over my head! 🥵

**Comment by AluminiumOxide** [comment]
> no sir! man!!!

While selective_scan in **man**ba-ssh has its own idea, amazing like a school of KND crawling over my head! 🥵🥵🥵

**Comment by qiyun71** [comment]
![IMG_20240420_013255_714.jpg](https://github.com/zjukg/MyGO/assets/53337859/f397192c-c1b3-4755-a151-7bb1f900c77c)
