### ISSUE TITLE
请问跑MKG-W数据集图像和文本的token embedding在哪找呢

### ISSUE THREAD

**Issue by teatimekon** [zjukg/MyGO#21]

**Comment by Zhang-Each** [comment]
你好，就在tokens目录下面，MKG-W开头的两个文件里。

**Comment by teatimekon** [comment]
> 你好，就在tokens目录下面，MKG-W开头的两个文件里。

谢谢你，那视觉和文本的嵌入也是用 visual.pth 和 save_token_embedding 生成的texual.pth 吗

**Comment by Zhang-Each** [comment]
是的，因为在不同的数据集上是统一用的这两个.pth文件里的token作为code book，他们和具体的知识图谱无关，是对应预训练模型BEiT和BERT的产物。

**Comment by lynnkyle** [comment]
请问作者visual.pth 是huggingface 那个预训练模型生成的，huggingface没找到相关beit预训练模型生成

**Comment by Zhang-Each** [comment]
> 请问作者visual.pth 是huggingface 那个预训练模型生成的，huggingface没找到相关beit预训练模型能生成visual.pth中保存的二维权重

我是在BEiT论文的github仓库里找到的下载链接，你可以通过原论文找到。huggingface上应该没有
