### ISSUE TITLE
🌟🌟🌟🌟🌟请大家多关注论文内容，少刷梗。谢谢大家🙏

### ISSUE THREAD

**Issue by Zhang-Each** [zjukg/MyGO#6]
请大家多关注论文内容，少刷梗。谢谢大家🙏

**Comment by AluminiumOxide** [comment]
Kirakira Dokidoki~!!!
ᕕ(◠ڼ◠)ᕗ

**Comment by yuyuyuger** [comment]
Can you provide approximately DB15K of image data? Thank you！

**Comment by Zhang-Each** [comment]
> Can you provide approximately DB15K of image data? Thank you！

Hello, the original data scale is quite large. You can download the original images from https://github.com/quqxui/MMRNS 
The download link is in the README.

**Comment by sandyzikun** [comment]
Or provide just 1 issue for MyGO-fans to chat? I don't know if this would solve the problem.
